### ISSUE TITLE
ValueError: Need to enable queue to use generators.

### ISSUE THREAD

**Issue by balala8** [OutofAi/OutofFocus#1]
This may be caused by the wrong version of the dependency.

```
Traceback (most recent call last):
File "/home/yongfang/miniconda3/envs/diffusers/lib/python3.9/site-packages/gradio/routes.py", line 534, in predict
output = await route_utils.call_process_api(
File "/home/yongfang/miniconda3/envs/diffusers/lib/python3.9/site-packages/gradio/route_utils.py", line 226, in call_process_api
output = await app.get_blocks().process_api(
File "/home/yongfang/miniconda3/envs/diffusers/lib/python3.9/site-packages/gradio/blocks.py", line 1550, in process_api
result = await self.call_function(
File "/home/yongfang/miniconda3/envs/diffusers/lib/python3.9/site-packages/gradio/blocks.py", line 1193, in call_function raise ValueError("Need to enable queue to use generators.") 
ValueError: Need to enable queue to use generators.
```
Adding this `enable_queue` parameter to the code 563 line can solve it

`demo.launch(share=args.share,enable_queue=True)`

**Comment by OutofAi** [comment]
I think enable_queue=True is deprecated, I added demo.queue() to the code now, hopefully that will fix the issue
