### ISSUE TITLE
Error After Install

### ISSUE THREAD

**Issue by y0himba** [OutofAi/OutofFocus#3]
Followed the installation instructions and tried to run `python app.py`

Windows 11, nVidia 4070 ti, 32GB RAM, CUDA installed and in the path. 

Pretty sure the Huggingface token is out of date as is listed below, and it should detect that xFormers needs updated to match requirements?

```
PS C:\Tools\OutofFocus> python app.py
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.4.0+cpu)
    Python  3.10.11 (you have 3.10.11)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Couldn't connect to the Hub: 401 Client Error. (Request ID: Root=1-66e448f4-7e8e4ccd3e003636429671bb;07c40fdc-d63b-42cf-a8db-d491357754b3)

Repository Not Found for url: https://huggingface.co/api/models/stabilityai/stable-diffusion-2-1-base.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
User Access Token "Huggingface" is expired.
Will try to load from local cache.
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Python310\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/stabilityai/stable-diffusion-2-1-base

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1291, in download
    info = model_info(pretrained_model_name, token=token, revision=revision)
  File "C:\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\huggingface_hub\hf_api.py", line 2373, in model_info
    hf_raise_for_status(r)
  File "C:\Python310\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66e448f4-7e8e4ccd3e003636429671bb;07c40fdc-d63b-42cf-a8db-d491357754b3)

Repository Not Found for url: https://huggingface.co/api/models/stabilityai/stable-diffusion-2-1-base.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
User Access Token "Huggingface" is expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Tools\OutofFocus\app.py", line 38, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(model_id).to("cuda")
  File "C:\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 699, in from_pretrained
    cached_folder = cls.download(
  File "C:\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1536, in download
    raise EnvironmentError(
OSError: Cannot load model stabilityai/stable-diffusion-2-1-base: model is not cached locally and an error occurred while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.
PS C:\Tools\OutofFocus>
```

**Comment by y0himba** [comment]
As for the CUDA error.  I have tried installing the WHL manually as well.  I still get the +CPU version.

```
PS C:\Tools\OutofFocus> pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch in c:\python310\lib\site-packages (2.4.0)
Requirement already satisfied: torchvision in c:\python310\lib\site-packages (0.19.0)
Requirement already satisfied: torchaudio in c:\python310\lib\site-packages (2.4.0)
Requirement already satisfied: filelock in c:\python310\lib\site-packages (from torch) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\python310\lib\site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in c:\python310\lib\site-packages (from torch) (1.13.2)
Requirement already satisfied: networkx in c:\python310\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\python310\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in c:\python310\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: numpy<2 in c:\python310\lib\site-packages (from torchvision) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\python310\lib\site-packages (from torchvision) (10.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\python310\lib\site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\python310\lib\site-packages (from sympy->torch) (1.3.0)
PS C:\Tools\OutofFocus>
```

```
PS C:\Tools\OutofFocus> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.rand(5, 3)
>>> print(x)
tensor([[0.1011, 0.6958, 0.7145],
        [0.7449, 0.1848, 0.0927],
        [0.8621, 0.8057, 0.3278],
        [0.0315, 0.6088, 0.2109],
        [0.8616, 0.3487, 0.8272]])
>>>
```

**Comment by OutofAi** [comment]
The token being out of date, is usually from the user's side, not from our side, you can remove the token or update your token on hugginface page for your account.

The cuda error, by just looking at the first line, seems to be a discrepancy between xformers and torch on your machine, am not sure why! we didn't enable enable_xformers_memory_efficient_attention in our code, so not sure why it's using xformers unless it's enabled by an environment variable on your machine, but I could recommend reinstalling xformers by running this

`pip install xformers  --force-reinstall`

**Comment by y0himba** [comment]
I am honestly not intelligent enough to use this lol.  Or too old. 

I also tried purging pip's cache and ` --no-cache-dir`


```
C:\Tools\OutofFocus>pip install xformers  --force-reinstall
Collecting xformers
  Using cached xformers-0.0.28.post1.tar.gz (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\y0himba\AppData\Local\Temp\pip-build-env-ew9arrh5\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\y0himba\AppData\Local\Temp\pip-build-env-ew9arrh5\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\y0himba\AppData\Local\Temp\pip-build-env-ew9arrh5\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\y0himba\AppData\Local\Temp\pip-build-env-ew9arrh5\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

C:\Tools\OutofFocus>
```

**Comment by tommcg** [comment]
Same thing'ish. Transformers won't install. I updated my hugging face key. That didn't fix it. Fooocus runs normal..this distro, not so much. Any tips? This looks very interesting to take a look at. Also, how do you get your logs/code inside that text area instead of grey like mine? 

<code>L:\Skynet\OutOfFocus\OutofFocus>python app.py
vae\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.51it/s]
Traceback (most recent call last):
  File "L:\Skynet\OutOfFocus\OutofFocus\app.py", line 38, in <module>
    pipe = StableDiffusionPipeline.from_pretrained(model_id).to("cuda")
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 815, in to
    module.to(device, dtype)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2905, in to
    return super().to(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

L:\Skynet\OutOfFocus\OutofFocus></code>

**Comment by OutofAi** [comment]
The other thing I can recommend is to run it in a virtual env, so there is no package conflict, something like this:

`python -m venv venv`

and then 

`.\venv\Scripts\activate`

and now that you virtual environment is enabled try to install the requirements again and run the app, it will install everything in a virtual environment. like a clean installation, you can deactivate it whenever you done with running the project

`.\venv\Scripts\deactivate`

you can also delete the virtual environment if you don't want it anymore and you need the space by deleting the venv folder that it creates

**Comment by tommcg** [comment]
> The other thing I can recommend is to run it in a virtual env, so there is no package conflict, something like this:
> 
> `python -m venv venv`
> 
> and then
> 
> `.\venv\Scripts\activate`
> 
> and now that you virtual environment is enabled try to install the requirements again and run the app, it will install everything in a virtual environment. like a clean installation, you can deactivate it whenever you done with running the project
> 
> `.\venv\Scripts\deactivate`
> 
> you can also delete the virtual environment if you don't want it anymore and you need the space by deleting the venv folder that it creates

That worked perfectly. Is there any reason setting up an env isn't part of the default design? 

-T

**Comment by OutofAi** [comment]
Python modules can end up becoming messy, as you experienced, developers tempt to create virtual environments to isolate that from future issues, and also projects are developed with modules with specific versions that people don't want to interfere with their global modules, hence creating virtual environment

**Comment by y0himba** [comment]
I feel like an idiot.  I should have known or tried a venv.   Thank you.  Once I renewed my Huggingface token, works swimmingly.  Thank you for the help!
